---
title: "BRH connect"
author: "Lebron James"
date: "`r Sys.Date()`"
output: 
 flexdashboard::flex_dashboard:
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(XML)
library(xml2)
library(rvest)
library(htmlTable)
library(dplyr)
library(shiny)
library(ggplot2)
library(plotly)
library(formattable)
```


```{r main, include=FALSE}
#Importation des données 
# Taux du jour HT 
url_tdj="https://www.brh.ht/taux-du-jour/"
dataread_tdj=rvest::read_html(url_tdj)
tableaux_tdj=rvest::html_table(dataread_tdj)
data.frame(tableaux_tdj)
TauxDuJour=data.frame(tableaux_tdj)


# Taux affichés par les banques HT  
url_tapb="https://www.brh.ht/taux-affiches-par-les-banques-et-les-agents-de-change-2/"
dataread_tapb=rvest::read_html(url_tapb)
tableaux_tapb=rvest::html_table(dataread_tapb)
data.frame(tableaux_tapb)
TauxAffichesParLesBanques=data.frame(tableaux_tapb)

# Rename

names(TauxAffichesParLesBanques)<-c("CATEGORIES","ACHATS","VENTES",'SPREAD')
names(TauxDuJour)<-c("CATEGORIES","ACHATS","VENTES",'SPREAD')


#Extraction

TAPB<-TauxAffichesParLesBanques[c(2:8),]

TDJ<-TauxDuJour[c(2,4,7),]

# Conversion

TAPB$CATEGORIES<-as.character(as.character(TAPB$CATEGORIES))
TAPB$ACHATS<-as.numeric(as.character(TAPB$ACHATS))
TAPB$VENTES<-as.numeric(as.character(TAPB$VENTES))
TAPB$SPREAD<-as.numeric(as.character(TAPB$SPREAD))
TAPB

TDJ$ACHATS<-as.numeric(as.character(TDJ$ACHATS))
TDJ$VENTES<-as.numeric(as.character(TDJ$VENTES))
TDJ$SPREAD<-as.numeric(as.character(TDJ$SPREAD))
TDJ

```


Taux de change Table
===============================================================================

### Tableau : Taux du jours

```{r echo=FALSE}
formattable(TDJ)

```

```{r echo=FALSE}
formattable(TAPB)

```


Taux de change Moyen 
==============================================================================

### Taux des différents marchés à l'achat et à la vente

```{r echo=FALSE}
#Graphe du Taux des différents marchés à l'achat
library(ggplot2)
library(reshape2)
library(melt)

# Create data
data <- data.frame(
  name=CATEGORIES,
  value=ACHATS,
  value2=VENTES
)

# Melt data
data <- melt(data,id="name")

# Plot
ggplot(data,aes(x=name,y=value,fill=variable)) +
  geom_bar(stat="identity",position="dodge") +
  scale_y_continuous(name="value",sec.axis = sec_axis(~./10,name = "value2")) +
  theme(legend.position="top")


```



Taux pratiqué par les Banques
================================================================================
### Taux pratiqué par les banques à la vente

```{r echo=FALSE}
 TAPBA<- ggplot(data = TAPB, aes(x = CATEGORIES,y=ACHATS,fill = CATEGORIES)) +
            geom_col(just = 0.5)
plot3<-ggplotly(TAPBA)

TAPBV<- ggplot(data = TAPB, aes(x = CATEGORIES,y=VENTES,fill = CATEGORIES)) +
            geom_col(just = 0.5)
plot4<-ggplotly(TAPBV)

# Afficher les graphiques dans une grille 2x1
subplot(
  plot3, 
  plot4,
  nrows  = 2,
  shareX = TRUE, 
  titleX = FALSE, 
  titleY = TRUE,
  margin = 0.05
)

```
